import type { Metadata } from "next"
import "./globals.css"
import { QueryProvider } from "@/providers/query-provider";

export const metadata: Metadata = {
  title: "FABR-NETWORK-ADM",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  )
}
